# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi/openapi.json:
  operation-4xx-response:
    - "#/paths/~1health/get/responses"
    - "#/paths/~1health~1live/get/responses"
openapi/openapi.yaml:
  operation-4xx-response:
    - "#/paths/~1health/get/responses"
    - "#/paths/~1health~1live/get/responses"
