/**
 * The per-user head `sync_heads` (API §9.2, §9.5; DESIGN §3.5–3.8): the user mutex, the `seq` counter shared by both
 * streams, the cursor `epoch` and `floor_seq` (always 0 in the MVP).
 *
 * - {@link lockUser} is the **first statement** of every serializable write of a user (`/sync` with ops, a new
 *   device, password change, recover, revoke-others, account deletion): `SELECT … FROM sync_heads … FOR UPDATE`.
 *   PostgreSQL locks the row; on SQLite `StripRowLocksPlugin` removes `FOR UPDATE` and `BEGIN IMMEDIATE` already made
 *   the transaction the only writer. `users` is never locked.
 * - {@link readHead} reads the head in `db.read` (the page of `/sync` is read after the write committed).
 * - {@link insertHead} creates the head together with the user (registration, `melogold user add`).
 * - A missing head is a bug-tolerant situation (m7): both helpers throw `MissingHeadError`, the transaction runner
 *   rolls back, calls {@link ensureHead} in a short write transaction and runs the callback once more.
 */
import { randomBytes } from "node:crypto";
import type { Kysely, Selectable } from "kysely";
import { MissingHeadError, TxRuleError, assertFirstStatementOfWrite, currentTxScope } from "./tx.ts";
import type { TxRunner } from "./tx.ts";
import type { Database, SyncHeadsTable } from "./types.ts";

export type Head = Readonly<{
  userId: string;
  /** 8 lowercase hex characters; a new one invalidates every cursor of the user (restore, DESIGN §3.15). */
  epoch: string;
  /** The last `seq` handed out; the next write of the user uses `seq + 1`. */
  seq: number;
  floorSeq: number;
  updatedAt: number;
}>;

export const EPOCH_PATTERN = /^[0-9a-f]{8}$/;

/** A random cursor epoch (API §1.6 `Cursor`: `<epoch 8 hex>.<lib>.<hist>`). Generated by TS, never by SQL. */
export function newEpoch(): string {
  return randomBytes(4).toString("hex");
}

function toHead(row: Selectable<SyncHeadsTable>): Head {
  return Object.freeze({
    userId: row.user_id,
    epoch: row.epoch,
    seq: row.seq,
    floorSeq: row.floor_seq,
    updatedAt: row.updated_at,
  });
}

/**
 * The user mutex (API §9.5). Must be the first statement of a `db.write` callback, otherwise it throws `TxRuleError`:
 * a statement before it would read or write without the lock.
 * @throws MissingHeadError when the user has no head (the runner then calls {@link ensureHead} and retries).
 */
export async function lockUser(q: Kysely<Database>, userId: string): Promise<Head> {
  assertFirstStatementOfWrite("lockUser");
  const row = await q.selectFrom("sync_heads").selectAll().where("user_id", "=", userId).forUpdate().executeTakeFirst();
  if (!row) throw new MissingHeadError(userId);
  return toHead(row);
}

/**
 * The head without a lock, for `db.read` (one snapshot with the rows it describes).
 * @throws MissingHeadError when the user has no head.
 */
export async function readHead(q: Kysely<Database>, userId: string): Promise<Head> {
  const row = await q.selectFrom("sync_heads").selectAll().where("user_id", "=", userId).executeTakeFirst();
  if (!row) throw new MissingHeadError(userId);
  return toHead(row);
}

/**
 * Creates the head of a user created in the same transaction (registration, `melogold user add`).
 * @param now epoch milliseconds (the service's clock).
 */
export async function insertHead(
  q: Kysely<Database>,
  userId: string,
  now: number,
  epoch: string = newEpoch(),
): Promise<Head> {
  if (!EPOCH_PATTERN.test(epoch)) throw new TxRuleError(`epoch must be 8 lowercase hex characters, got "${epoch}"`);
  await q.insertInto("sync_heads").values({ user_id: userId, epoch, seq: 0, floor_seq: 0, updated_at: now }).execute();
  return Object.freeze({ userId, epoch, seq: 0, floorSeq: 0, updatedAt: now });
}

/**
 * Moves the head to `seq` after a write that handed out numbers up to `seq` (inside the transaction that holds
 * {@link lockUser}). The counter never goes back.
 * @throws TxRuleError outside `db.write`, or when the head is missing or already beyond `seq`.
 */
export async function bumpHead(q: Kysely<Database>, userId: string, seq: number, now: number): Promise<void> {
  if (currentTxScope()?.kind !== "write") throw new TxRuleError("bumpHead must be called inside db.write");
  const result = await q
    .updateTable("sync_heads")
    .set({ seq, updated_at: now })
    .where("user_id", "=", userId)
    .where("seq", "<=", seq)
    .executeTakeFirst();
  if (result.numUpdatedRows !== 1n) {
    throw new TxRuleError(`bumpHead: the head of ${userId} is missing or beyond seq ${seq}`);
  }
}

/**
 * Creates the missing head of an existing user in its own short write transaction (API §9.5, m7):
 * `INSERT … SELECT … FROM users WHERE id = ? ON CONFLICT (user_id) DO NOTHING`, so a concurrent creation and a
 * missing user are both handled without catching a constraint error.
 * @returns whether the head exists now (`false`: there is no such user).
 */
export async function ensureHead(db: Pick<TxRunner<Database>, "write">, userId: string, now: number): Promise<boolean> {
  const epoch = newEpoch();
  return db.write(async (q) => {
    await q
      .insertInto("sync_heads")
      .columns(["user_id", "epoch", "seq", "floor_seq", "updated_at"])
      .expression(
        q
          .selectFrom("users")
          .select((eb) => [
            eb.ref("id").as("user_id"),
            eb.val(epoch).as("epoch"),
            eb.lit(0).as("seq"),
            eb.lit(0).as("floor_seq"),
            eb.val(now).as("updated_at"),
          ])
          .where("id", "=", userId),
      )
      .onConflict((conflict) => conflict.column("user_id").doNothing())
      .execute();
    const head = await q.selectFrom("sync_heads").select("user_id").where("user_id", "=", userId).executeTakeFirst();
    return head !== undefined;
  });
}
