// Generated by scripts/gen-schema-sql.ts from src/db/migrations (npm run schema:sql). Do not edit.
/**
 * Kysely table types of the schema in API §9.2. Column types follow API §9.1: `ID`, `TXT` and `JSON` are strings
 * (`JSON` holds JSON text, see `codecs.ts`), `INT`, `BIG` and `TS` (epoch milliseconds) are numbers, `BOOL` is
 * `0 | 1`. A column with a `DEFAULT` is `Generated<…>`: optional on insert.
 */
import type { Generated } from "kysely";

export type ServerMetaTable = {
  key: string; // ID
  value: string; // TXT
};

export type UsersTable = {
  id: string; // ID
  login: string; // ID
  password_hash: string; // TXT
  auth_version: Generated<number>; // INT
  password_changed_at: number; // TS
  recovery_code_hash: string; // ID
  recovery_code_created_at: number; // TS
  recovery_code_confirmed_at: number | null; // TS
  created_by: Generated<string>; // TXT
  deleted_at: number | null; // TS
  created_at: number; // TS
  updated_at: number; // TS
};

export type DevicesTable = {
  id: string; // ID
  user_id: string; // ID
  hwid_hash: string; // ID
  reported_name: string; // TXT
  custom_name: string | null; // TXT
  platform: string; // TXT
  os_version: string | null; // TXT
  model: string | null; // TXT
  client_version: string | null; // TXT
  linked_via: string; // TXT
  linked_by_device_id: string | null; // ID
  created_at: number; // TS
  last_seen_at: number; // TS
  last_sync_at: number | null; // TS
};

export type RefreshTokensTable = {
  id: string; // ID
  user_id: string; // ID
  device_id: string; // ID
  token_hash: string; // ID
  expires_at: number; // TS
  rotated_to_id: string | null; // ID
  rotation_grace_expires_at: number | null; // TS
  revoked_at: number | null; // TS
  confirmed_at: number | null; // TS
  created_at: number; // TS
};

export type AuthThrottleTable = {
  scope: string; // ID
  key_hash: string; // ID
  failures: Generated<number>; // INT
  window_start: number; // TS
  locked_until: number | null; // TS
  updated_at: number; // TS
};

export type DeviceLinksTable = {
  id: string; // ID
  mode: string; // TXT
  status: string; // TXT
  token_hash: string; // ID
  code_hash: string; // ID
  poll_secret_hash: string | null; // ID
  user_id: string | null; // ID
  approver_device_id: string | null; // ID
  claimant_hwid_hash: string | null; // ID
  claimant_name: string | null; // TXT
  claimant_platform: string | null; // TXT
  claimant_os_version: string | null; // TXT
  claimant_model: string | null; // TXT
  claimant_client_version: string | null; // TXT
  verify_code: string | null; // TXT
  deny_reason: string | null; // TXT
  creator_net: string | null; // TXT
  other_net: string | null; // TXT
  result_device_id: string | null; // ID
  result_refresh_id: string | null; // ID
  created_at: number; // TS
  expires_at: number; // TS
  claimed_at: number | null; // TS
  decided_at: number | null; // TS
  completed_at: number | null; // TS
};

export type SyncHeadsTable = {
  user_id: string; // ID
  epoch: string; // ID
  seq: Generated<number>; // BIG
  floor_seq: Generated<number>; // BIG
  updated_at: number; // TS
};

export type SyncOpsTable = {
  user_id: string; // ID
  seq: number; // BIG
  op_id: string; // ID
  device_id: string | null; // ID
  device_name: string | null; // TXT
  kind: string; // TXT
  payload: string; // JSON
  status: string; // TXT
  code: string | null; // TXT
  result: string | null; // JSON
  client_at: number; // TS
  eff_at: number; // TS
  base_seq: number | null; // BIG
  pre_image: string | null; // JSON
  server_at: number; // TS
};

export type SyncTracksTable = {
  user_id: string; // ID
  video_id: string; // ID
  title: string; // TXT
  artists_text: string | null; // TXT
  artists: string | null; // JSON
  album_id: string | null; // ID
  album_title: string | null; // TXT
  duration_ms: number | null; // BIG
  duration_text: string | null; // TXT
  thumbnail_url: string | null; // TXT
  explicit: Generated<0 | 1>; // BOOL
  video_type: string | null; // TXT
  stub: Generated<0 | 1>; // BOOL
  seq: number; // BIG
  updated_at: number; // TS
};

export type SyncLikesTable = {
  user_id: string; // ID
  video_id: string; // ID
  liked: 0 | 1; // BOOL
  liked_at: number | null; // TS
  seq: number; // BIG
  clk_at: number; // TS
  clk_dev: string | null; // ID
};

export type SyncBookmarksTable = {
  user_id: string; // ID
  type: string; // ID
  browse_id: string; // ID
  bookmarked: 0 | 1; // BOOL
  bookmarked_at: number | null; // TS
  title: string | null; // TXT
  subtitle: string | null; // TXT
  thumbnail_url: string | null; // TXT
  year: string | null; // TXT
  seq: number; // BIG
  clk_at: number; // TS
  clk_dev: string | null; // ID
};

export type SyncPlaylistsTable = {
  user_id: string; // ID
  id: string; // ID
  name: string; // TXT
  browse_id: string | null; // ID
  thumbnail_url: string | null; // TXT
  created_at: number; // TS
  deleted: Generated<0 | 1>; // BOOL
  deleted_at: number | null; // TS
  deleted_seq: number | null; // BIG
  item_count: Generated<number>; // INT
  seq: number; // BIG
  clk_at: number; // TS
  clk_dev: string | null; // ID
};

export type SyncPlaylistItemsTable = {
  user_id: string; // ID
  playlist_id: string; // ID
  video_id: string; // ID
  present: 0 | 1; // BOOL
  sort_key: string; // ID
  added_at: number; // TS
  seq: number; // BIG
  mem_seq: number; // BIG
  mem_at: number; // TS
  mem_dev: string | null; // ID
  pos_seq: number; // BIG
  pos_at: number; // TS
  pos_dev: string | null; // ID
};

export type PlaybackStateTable = {
  user_id: string; // ID
  rev: number; // BIG
  cleared: Generated<0 | 1>; // BOOL
  device_id: string; // ID
  device_name: string | null; // TXT
  session_id: string; // ID
  queue_version: number; // BIG
  queue: string; // JSON
  idx: number; // INT
  position_ms: number; // BIG
  duration_ms: number | null; // BIG
  playing: 0 | 1; // BOOL
  state_at: number; // TS
  updated_at: number; // TS
  handoff_device_id: string | null; // ID
  handoff_session_id: string | null; // ID
  handoff_at: number | null; // TS
};

export type PlayEventsTable = {
  user_id: string; // ID
  event_id: string; // ID
  video_id: string; // ID
  played_at: number; // TS
  play_time_ms: number; // INT
  in_history: 0 | 1; // BOOL
  counts_playtime: 0 | 1; // BOOL
  device_id: string | null; // ID
  seq: number | null; // BIG
  received_at: number; // TS
};

export type PlayStatsTable = {
  user_id: string; // ID
  video_id: string; // ID
  total_ms: Generated<number>; // BIG
  last_played_at: number | null; // TS
  seq: number; // BIG
};

export type PlayForgetsTable = {
  user_id: string; // ID
  video_id: string; // ID
  events_before: number; // TS
  total_before: number | null; // TS
  seq: number; // BIG
};

export type Database = {
  server_meta: ServerMetaTable;
  users: UsersTable;
  devices: DevicesTable;
  refresh_tokens: RefreshTokensTable;
  auth_throttle: AuthThrottleTable;
  device_links: DeviceLinksTable;
  sync_heads: SyncHeadsTable;
  sync_ops: SyncOpsTable;
  sync_tracks: SyncTracksTable;
  sync_likes: SyncLikesTable;
  sync_bookmarks: SyncBookmarksTable;
  sync_playlists: SyncPlaylistsTable;
  sync_playlist_items: SyncPlaylistItemsTable;
  playback_state: PlaybackStateTable;
  play_events: PlayEventsTable;
  play_stats: PlayStatsTable;
  play_forgets: PlayForgetsTable;
};
