/**
 * `npm run openapi` (second part): writes `spec/error-codes.json`, the machine-readable registry of API §2.2 (HTTP
 * error codes with status, message and details) and §2.3 (op result codes), from `src/http/error-codes.ts`.
 * Clients branch only on `code` (API §2.2). CC0-1.0 (DESIGN §12, question 2; `spec/LICENSE`).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ALL_ERROR_CODES, CLIENT_LOCAL_OP_CODES, ERROR_CODES, OP_RESULT_CODES } from "../src/http/error-codes.ts";
import type { OpResultCode } from "../src/http/error-codes.ts";

export type ErrorCodesDocument = Readonly<{
  $comment: string;
  license: "CC0-1.0";
  errors: readonly Readonly<{
    code: string;
    status: number;
    message: string;
    details: Readonly<{ required: readonly string[]; optional: readonly string[] }>;
  }>[];
  opResults: readonly Readonly<{ code: string; status: string }>[];
  clientLocalOpCodes: readonly string[];
}>;

/** The document of `spec/error-codes.json`, in the order of API §2.2 and §2.3. */
export function errorCodesDocument(): ErrorCodesDocument {
  return {
    $comment:
      "Melogold API error codes (docs/API.md §2.2, §2.3). Generated by scripts/gen-error-codes.ts from " +
      "src/http/error-codes.ts (npm run openapi). Do not edit.",
    license: "CC0-1.0",
    errors: ALL_ERROR_CODES.map((code) => {
      const spec = ERROR_CODES[code];
      return {
        code,
        status: spec.status,
        message: spec.message,
        details: { required: [...spec.required], optional: [...spec.optional] },
      };
    }),
    opResults: (Object.keys(OP_RESULT_CODES) as OpResultCode[]).map((code) => ({
      code,
      status: OP_RESULT_CODES[code].status,
    })),
    clientLocalOpCodes: [...CLIENT_LOCAL_OP_CODES],
  };
}

export function errorCodesJson(): string {
  return `${JSON.stringify(errorCodesDocument(), null, 2)}\n`;
}

if (import.meta.main) {
  const root = new URL("../", import.meta.url);
  mkdirSync(new URL("spec/", root), { recursive: true });
  const file = new URL("spec/error-codes.json", root);
  writeFileSync(file, errorCodesJson());
  process.stdout.write(`wrote ${fileURLToPath(file)}\n`);
}
