/**
 * `npm run openapi` (with `gen-error-codes.ts`): builds the application on `sqlite::memory:` (DESIGN §6.2: tests and
 * OpenAPI generation only) and writes the document every client team generates code from (API §1.1):
 * - `openapi/openapi.json`, the same document the server serves at `GET /openapi.json`;
 * - `openapi/openapi.yaml`, the same in YAML with the SPDX header.
 *
 * Both are CC0-1.0 (DESIGN §12, question 2; `openapi/LICENSE`). The output depends only on the code: no environment,
 * time or randomness, so `npm run openapi:check` can compare it with the committed files.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildApp, createFastify } from "../src/app.ts";
import { parseEnv } from "../src/config/env.ts";
import { deriveSubkeys } from "../src/config/secret-key.ts";
import { createAppContext } from "../src/context.ts";
import { createDb } from "../src/db/index.ts";

export const SPDX_HEADER = "SPDX-License-Identifier: CC0-1.0";
const GENERATED_BY = "Generated by scripts/gen-openapi.ts from the code (npm run openapi). Do not edit.";

/** A fixed identity: the document never contains it, but the context needs one. */
const GENERATOR_SERVER_ID = "00000000-0000-4000-8000-000000000000";

export type OpenapiDocuments = Readonly<{ document: Record<string, unknown>; json: string; yaml: string }>;

/** Builds the app without listening and renders its OpenAPI document. */
export async function generateOpenapi(): Promise<OpenapiDocuments> {
  const dataDir = mkdtempSync(join(tmpdir(), "melogold-openapi-"));
  const env = parseEnv({
    NODE_ENV: "test",
    DATABASE_URL: "sqlite::memory:",
    DATA_DIR: dataDir,
    LOG_LEVEL: "silent",
    RATE_LIMIT_ENABLED: "false",
  });
  const db = createDb(env);
  try {
    const ctx = createAppContext({
      env,
      db,
      serverId: GENERATOR_SERVER_ID,
      keys: deriveSubkeys(Buffer.alloc(32), GENERATOR_SERVER_ID),
    });
    const app = await buildApp(ctx, { app: createFastify(env) });
    await app.ready();
    const document = app.swagger() as Record<string, unknown>;
    const yamlBody = app.swagger({ yaml: true });
    await app.close();
    return Object.freeze({
      document,
      json: `${JSON.stringify(document, null, 2)}\n`,
      yaml: `# ${SPDX_HEADER}\n# ${GENERATED_BY}\n${yamlBody.endsWith("\n") ? yamlBody : `${yamlBody}\n`}`,
    });
  } finally {
    await db.destroy();
    rmSync(dataDir, { recursive: true, force: true });
  }
}

if (import.meta.main) {
  const root = new URL("../", import.meta.url);
  const { json, yaml } = await generateOpenapi();
  mkdirSync(new URL("openapi/", root), { recursive: true });
  writeFileSync(new URL("openapi/openapi.json", root), json);
  writeFileSync(new URL("openapi/openapi.yaml", root), yaml);
  process.stdout.write(`wrote ${fileURLToPath(new URL("openapi/", root))}openapi.{json,yaml}\n`);
}
