/**
 * `npm run schema:sql`: renders the migrations (src/db/migrations) without a database and writes
 * - docs/schema.sqlite.sql and docs/schema.postgres.sql: the DDL each dialect executes (API §9.1 rule 9);
 * - src/db/schema.snapshot.json: tables, columns (logical type, nullability) and indexes, compared with the live
 *   database at startup (`schema-check.ts`, DESIGN §6.2);
 * - src/db/types.ts: the Kysely table types.
 *
 * `npm run schema:sql:check` regenerates and fails when the committed files differ.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { ddl, recordingKysely } from "../src/db/ddl.ts";
import type { LogicalType, SchemaModel, SqlDialect } from "../src/db/ddl.ts";
import { MIGRATIONS } from "../src/db/migrations/index.ts";

const root = new URL("../", import.meta.url);
const GENERATED_BY = "Generated by scripts/gen-schema-sql.ts from src/db/migrations (npm run schema:sql). Do not edit.";

type Rendered = { model: SchemaModel; sections: { migration: string; statements: string[] }[] };

async function render(dialect: SqlDialect): Promise<Rendered> {
  const d = ddl(dialect);
  const { kysely, statements } = recordingKysely(dialect);
  const sections: Rendered["sections"] = [];
  for (const migration of MIGRATIONS) {
    const start = statements.length;
    await migration.up(kysely, d);
    sections.push({ migration: migration.name, statements: statements.slice(start) });
  }
  await kysely.destroy();
  return { model: d.model, sections };
}

function sqlFile(dialect: SqlDialect, rendered: Rendered): string {
  const title = dialect === "sqlite" ? "SQLite" : "PostgreSQL";
  const header = [
    `-- Melogold database schema, ${title}.`,
    `-- ${GENERATED_BY}`,
    "-- Normative source: docs/API.md §9. Kysely creates kysely_migration and kysely_migration_lock itself.",
  ];
  if (dialect === "sqlite") {
    header.push(
      "-- A new database gets PRAGMA auto_vacuum = INCREMENTAL before the first table (src/db/dialect-sqlite.ts).",
    );
  }
  const body = rendered.sections.map(({ migration, statements }) => {
    const banner = `-- ===== ${migration} `.padEnd(80, "=");
    return [banner, ...statements.map((statement) => `${statement};`)].join("\n\n");
  });
  return `${header.join("\n")}\n\n${body.join("\n\n")}\n`;
}

type Snapshot = {
  $comment: string;
  migrations: string[];
  tables: Record<string, { columns: { name: string; type: LogicalType; nullable: boolean }[]; indexes: string[] }>;
};

function snapshot(model: SchemaModel): Snapshot {
  const tables: Snapshot["tables"] = {};
  for (const table of model.tables.values()) {
    tables[table.name] = {
      columns: table.columns.map((column) => ({ name: column.name, type: column.type, nullable: column.nullable })),
      indexes: [...table.indexes],
    };
  }
  return { $comment: GENERATED_BY, migrations: MIGRATIONS.map((migration) => migration.name), tables };
}

/** JSON with one line per column, so that the file reads like a table (Prettier keeps short objects inline). */
function snapshotJson(value: Snapshot): string {
  const j = (item: unknown) => JSON.stringify(item);
  const tables = Object.entries(value.tables).map(([name, table]) => {
    const columns = table.columns.map(
      (column) => `        { "name": ${j(column.name)}, "type": ${j(column.type)}, "nullable": ${j(column.nullable)} }`,
    );
    return [
      `    ${j(name)}: {`,
      `      "columns": [\n${columns.join(",\n")}\n      ],`,
      `      "indexes": ${j(table.indexes)}`,
      "    }",
    ].join("\n");
  });
  return [
    "{",
    `  "$comment": ${j(value.$comment)},`,
    `  "migrations": ${j(value.migrations)},`,
    `  "tables": {\n${tables.join(",\n")}\n  }`,
    "}",
    "",
  ].join("\n");
}

const TS_TYPES: Readonly<Record<LogicalType, string>> = {
  ID: "string",
  TXT: "string",
  JSON: "string",
  INT: "number",
  BIG: "number",
  TS: "number",
  BOOL: "0 | 1",
};

function pascalCase(name: string): string {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function typesFile(model: SchemaModel): string {
  const lines = [
    `// ${GENERATED_BY}`,
    "/**",
    " * Kysely table types of the schema in API §9.2. Column types follow API §9.1: `ID`, `TXT` and `JSON` are strings",
    " * (`JSON` holds JSON text, see `codecs.ts`), `INT`, `BIG` and `TS` (epoch milliseconds) are numbers, `BOOL` is",
    " * `0 | 1`. A column with a `DEFAULT` is `Generated<…>`: optional on insert.",
    " */",
    'import type { Generated } from "kysely";',
    "",
  ];
  const entries: string[] = [];
  for (const table of model.tables.values()) {
    const typeName = `${pascalCase(table.name)}Table`;
    entries.push(`  ${table.name}: ${typeName};`);
    lines.push(`export type ${typeName} = {`);
    for (const column of table.columns) {
      let type = TS_TYPES[column.type];
      if (column.hasDefault) type = `Generated<${type}>`;
      if (column.nullable) type = `${type} | null`;
      lines.push(`  ${column.name}: ${type}; // ${column.type}`);
    }
    lines.push("};", "");
  }
  lines.push("export type Database = {", ...entries, "};", "");
  return lines.join("\n");
}

async function prettierFormat(path: string, text: string): Promise<string> {
  const options = (await resolveConfig(path)) ?? {};
  return format(text, { ...options, filepath: path });
}

function modelsEqual(left: SchemaModel, right: SchemaModel): boolean {
  const describe = (model: SchemaModel) => JSON.stringify([...model.tables.values()]);
  return describe(left) === describe(right);
}

async function main(): Promise<void> {
  const sqlite = await render("sqlite");
  const postgres = await render("postgres");
  if (!modelsEqual(sqlite.model, postgres.model)) throw new Error("the dialects produced different schema models");

  const outputs: [string, string][] = [
    ["docs/schema.sqlite.sql", sqlFile("sqlite", sqlite)],
    ["docs/schema.postgres.sql", sqlFile("postgres", postgres)],
    ["src/db/schema.snapshot.json", snapshotJson(snapshot(sqlite.model))],
    ["src/db/types.ts", typesFile(sqlite.model)],
  ];
  for (const [relative, content] of outputs) {
    const path = fileURLToPath(new URL(relative, root));
    const text = relative.startsWith("docs/") ? content : await prettierFormat(path, content);
    writeFileSync(path, text);
    console.log(`wrote ${relative}`);
  }
}

await main();
