-- Melogold database schema, PostgreSQL.
-- Generated by scripts/gen-schema-sql.ts from src/db/migrations (npm run schema:sql). Do not edit.
-- Normative source: docs/API.md §9. Kysely creates kysely_migration and kysely_migration_lock itself.

-- ===== 0001_core =============================================================

CREATE TABLE server_meta (
  key   text COLLATE "C" NOT NULL PRIMARY KEY,
  value text NOT NULL
);

CREATE TABLE users (
  id                         text COLLATE "C" NOT NULL PRIMARY KEY,
  login                      text COLLATE "C" NOT NULL UNIQUE CHECK (length(login) BETWEEN 3 AND 64),
  password_hash              text NOT NULL,
  auth_version               integer NOT NULL DEFAULT 1,
  password_changed_at        bigint NOT NULL,
  recovery_code_hash         text COLLATE "C" NOT NULL CHECK (length(recovery_code_hash) = 64),
  recovery_code_created_at   bigint NOT NULL,
  recovery_code_confirmed_at bigint NULL,
  created_by                 text NOT NULL DEFAULT 'self',
  deleted_at                 bigint NULL,
  created_at                 bigint NOT NULL,
  updated_at                 bigint NOT NULL
);

CREATE INDEX users_deleted ON users (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE devices (
  id                  text COLLATE "C" NOT NULL PRIMARY KEY,
  user_id             text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hwid_hash           text COLLATE "C" NOT NULL CHECK (length(hwid_hash) = 64),
  reported_name       text NOT NULL CHECK (length(reported_name) BETWEEN 1 AND 64),
  custom_name         text NULL CHECK (custom_name IS NULL OR length(custom_name) BETWEEN 1 AND 64),
  platform            text NOT NULL CHECK (length(platform) BETWEEN 1 AND 16),
  os_version          text NULL,
  model               text NULL,
  client_version      text NULL,
  linked_via          text NOT NULL,
  linked_by_device_id text COLLATE "C" NULL,
  created_at          bigint NOT NULL,
  last_seen_at        bigint NOT NULL,
  last_sync_at        bigint NULL,
  UNIQUE (user_id, hwid_hash)
);

CREATE INDEX devices_last_seen ON devices (last_seen_at);

CREATE TABLE refresh_tokens (
  id                        text COLLATE "C" NOT NULL PRIMARY KEY,
  user_id                   text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id                 text COLLATE "C" NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  token_hash                text COLLATE "C" NOT NULL UNIQUE,
  expires_at                bigint NOT NULL,
  rotated_to_id             text COLLATE "C" NULL,
  rotation_grace_expires_at bigint NULL,
  revoked_at                bigint NULL,
  confirmed_at              bigint NULL,
  created_at                bigint NOT NULL
);

CREATE INDEX refresh_tokens_user ON refresh_tokens (user_id);

CREATE INDEX refresh_tokens_device ON refresh_tokens (device_id);

CREATE INDEX refresh_tokens_expires ON refresh_tokens (expires_at);

CREATE TABLE auth_throttle (
  scope        text COLLATE "C" NOT NULL,
  key_hash     text COLLATE "C" NOT NULL,
  failures     integer NOT NULL DEFAULT 0,
  window_start bigint NOT NULL,
  locked_until bigint NULL,
  updated_at   bigint NOT NULL,
  PRIMARY KEY (scope, key_hash)
);

-- ===== 0002_linking ==========================================================

CREATE TABLE device_links (
  id                      text COLLATE "C" NOT NULL PRIMARY KEY,
  mode                    text NOT NULL,
  status                  text NOT NULL,
  token_hash              text COLLATE "C" NOT NULL UNIQUE,
  code_hash               text COLLATE "C" NOT NULL UNIQUE,
  poll_secret_hash        text COLLATE "C" NULL UNIQUE,
  user_id                 text COLLATE "C" NULL REFERENCES users(id) ON DELETE CASCADE,
  approver_device_id      text COLLATE "C" NULL REFERENCES devices(id) ON DELETE SET NULL,
  claimant_hwid_hash      text COLLATE "C" NULL,
  claimant_name           text NULL,
  claimant_platform       text NULL,
  claimant_os_version     text NULL,
  claimant_model          text NULL,
  claimant_client_version text NULL,
  verify_code             text NULL CHECK (verify_code IS NULL OR length(verify_code) = 2),
  deny_reason             text NULL,
  creator_net             text NULL,
  other_net               text NULL,
  result_device_id        text COLLATE "C" NULL,
  result_refresh_id       text COLLATE "C" NULL,
  created_at              bigint NOT NULL,
  expires_at              bigint NOT NULL,
  claimed_at              bigint NULL,
  decided_at              bigint NULL,
  completed_at            bigint NULL
);

CREATE INDEX device_links_expires ON device_links (expires_at);

CREATE INDEX device_links_user ON device_links (user_id);

CREATE INDEX device_links_approver ON device_links (approver_device_id);

CREATE INDEX device_links_net ON device_links (creator_net) WHERE creator_net IS NOT NULL;

-- ===== 0003_sync =============================================================

CREATE TABLE sync_heads (
  user_id    text COLLATE "C" NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  epoch      text COLLATE "C" NOT NULL CHECK (length(epoch) = 8),
  seq        bigint NOT NULL DEFAULT 0,
  floor_seq  bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL
);

CREATE TABLE sync_ops (
  user_id     text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seq         bigint NOT NULL,
  op_id       text COLLATE "C" NOT NULL,
  device_id   text COLLATE "C" NULL,
  device_name text NULL,
  kind        text NOT NULL CHECK (length(kind) BETWEEN 1 AND 64),
  payload     text NOT NULL,
  status      text NOT NULL,
  code        text NULL,
  result      text NULL,
  client_at   bigint NOT NULL,
  eff_at      bigint NOT NULL,
  base_seq    bigint NULL,
  pre_image   text NULL,
  server_at   bigint NOT NULL,
  PRIMARY KEY (user_id, seq)
);

CREATE UNIQUE INDEX sync_ops_op ON sync_ops (user_id, op_id);

CREATE INDEX sync_ops_server_at ON sync_ops (server_at);

CREATE TABLE sync_tracks (
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  title         text NOT NULL,
  artists_text  text NULL,
  artists       text NULL,
  album_id      text COLLATE "C" NULL,
  album_title   text NULL,
  duration_ms   bigint NULL,
  duration_text text NULL,
  thumbnail_url text NULL,
  explicit      integer NOT NULL DEFAULT 0 CHECK (explicit IN (0,1)),
  video_type    text NULL,
  stub          integer NOT NULL DEFAULT 0 CHECK (stub IN (0,1)),
  seq           bigint NOT NULL,
  updated_at    bigint NOT NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX sync_tracks_pull ON sync_tracks (user_id, seq);

CREATE TABLE sync_likes (
  user_id  text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  liked    integer NOT NULL CHECK (liked IN (0,1)),
  liked_at bigint NULL,
  seq      bigint NOT NULL,
  clk_at   bigint NOT NULL,
  clk_dev  text COLLATE "C" NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX sync_likes_pull ON sync_likes (user_id, seq);

CREATE TABLE sync_bookmarks (
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text COLLATE "C" NOT NULL CHECK (length(type) BETWEEN 1 AND 16),
  browse_id     text COLLATE "C" NOT NULL CHECK (length(browse_id) BETWEEN 1 AND 64),
  bookmarked    integer NOT NULL CHECK (bookmarked IN (0,1)),
  bookmarked_at bigint NULL,
  title         text NULL,
  subtitle      text NULL,
  thumbnail_url text NULL,
  year          text NULL,
  seq           bigint NOT NULL,
  clk_at        bigint NOT NULL,
  clk_dev       text COLLATE "C" NULL,
  PRIMARY KEY (user_id, type, browse_id)
);

CREATE INDEX sync_bookmarks_pull ON sync_bookmarks (user_id, seq);

CREATE TABLE sync_playlists (
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  id            text COLLATE "C" NOT NULL,
  name          text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  browse_id     text COLLATE "C" NULL,
  thumbnail_url text NULL,
  created_at    bigint NOT NULL,
  deleted       integer NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
  deleted_at    bigint NULL,
  deleted_seq   bigint NULL,
  item_count    integer NOT NULL DEFAULT 0,
  seq           bigint NOT NULL,
  clk_at        bigint NOT NULL,
  clk_dev       text COLLATE "C" NULL,
  PRIMARY KEY (user_id, id)
);

CREATE INDEX sync_playlists_pull ON sync_playlists (user_id, seq);

CREATE INDEX sync_playlists_live_browse ON sync_playlists (user_id, browse_id) WHERE deleted = 0 AND browse_id IS NOT NULL;

CREATE TABLE sync_playlist_items (
  user_id     text COLLATE "C" NOT NULL,
  playlist_id text COLLATE "C" NOT NULL,
  video_id    text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  present     integer NOT NULL CHECK (present IN (0,1)),
  sort_key    text COLLATE "C" NOT NULL CHECK (length(sort_key) BETWEEN 1 AND 64),
  added_at    bigint NOT NULL,
  seq         bigint NOT NULL,
  mem_seq     bigint NOT NULL,
  mem_at      bigint NOT NULL,
  mem_dev     text COLLATE "C" NULL,
  pos_seq     bigint NOT NULL,
  pos_at      bigint NOT NULL,
  pos_dev     text COLLATE "C" NULL,
  PRIMARY KEY (user_id, playlist_id, video_id),
  FOREIGN KEY (user_id, playlist_id) REFERENCES sync_playlists (user_id, id) ON DELETE CASCADE
);

CREATE INDEX sync_items_pull ON sync_playlist_items (user_id, seq);

CREATE INDEX sync_items_order ON sync_playlist_items (user_id, playlist_id, sort_key, video_id) WHERE present = 1;

-- ===== 0004_playback =========================================================

CREATE TABLE playback_state (
  user_id            text COLLATE "C" NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  rev                bigint NOT NULL,
  cleared            integer NOT NULL DEFAULT 0 CHECK (cleared IN (0,1)),
  device_id          text COLLATE "C" NOT NULL,
  device_name        text NULL,
  session_id         text COLLATE "C" NOT NULL,
  queue_version      bigint NOT NULL CHECK (queue_version >= 0),
  queue              text NOT NULL,
  idx                integer NOT NULL CHECK (idx >= 0),
  position_ms        bigint NOT NULL CHECK (position_ms >= 0),
  duration_ms        bigint NULL,
  playing            integer NOT NULL CHECK (playing IN (0,1)),
  state_at           bigint NOT NULL,
  updated_at         bigint NOT NULL,
  handoff_device_id  text COLLATE "C" NULL,
  handoff_session_id text COLLATE "C" NULL,
  handoff_at         bigint NULL
);

CREATE INDEX playback_state_updated ON playback_state (updated_at);

-- ===== 0005_history ==========================================================

CREATE TABLE play_events (
  user_id         text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id        text COLLATE "C" NOT NULL,
  video_id        text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  played_at       bigint NOT NULL,
  play_time_ms    integer NOT NULL CHECK (play_time_ms BETWEEN 1 AND 86400000),
  in_history      integer NOT NULL CHECK (in_history IN (0,1)),
  counts_playtime integer NOT NULL CHECK (counts_playtime IN (0,1)),
  device_id       text COLLATE "C" NULL,
  seq             bigint NULL,
  received_at     bigint NOT NULL,
  PRIMARY KEY (user_id, event_id)
);

CREATE INDEX play_events_pull ON play_events (user_id, seq) WHERE seq IS NOT NULL;

CREATE INDEX play_events_video ON play_events (user_id, video_id, played_at);

CREATE INDEX play_events_time ON play_events (user_id, played_at);

CREATE INDEX play_events_recv ON play_events (user_id, received_at);

CREATE INDEX play_events_idem ON play_events (received_at) WHERE in_history = 0;

CREATE TABLE play_stats (
  user_id        text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id       text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  total_ms       bigint NOT NULL DEFAULT 0,
  last_played_at bigint NULL,
  seq            bigint NOT NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX play_stats_pull ON play_stats (user_id, seq);

CREATE TABLE play_forgets (
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      text COLLATE "C" NOT NULL CHECK (video_id = '*' OR length(video_id) = 11),
  events_before bigint NOT NULL,
  total_before  bigint NULL,
  seq           bigint NOT NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX play_forgets_pull ON play_forgets (user_id, seq);

-- ===== 0006_lyrics ===========================================================

CREATE TABLE lyrics (
  id            text COLLATE "C" NOT NULL PRIMARY KEY,
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  rev           bigint NOT NULL CHECK (rev >= 1),
  deleted       integer NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
  plain         text NULL,
  plain_source  text NULL,
  synced        text NULL,
  synced_format text NULL,
  synced_source text NULL,
  start_time_ms bigint NULL,
  language      text NULL,
  created_at    bigint NOT NULL,
  updated_at    bigint NOT NULL
);

CREATE UNIQUE INDEX lyrics_user_video ON lyrics (user_id, video_id);

CREATE UNIQUE INDEX lyrics_user_rev ON lyrics (user_id, rev);

CREATE INDEX lyrics_video ON lyrics (video_id, updated_at);

-- ===== 0007_overrides_pins ===================================================

CREATE TABLE sync_track_overrides (
  user_id      text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id     text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  title        text NULL,
  artists_text text NULL,
  album_title  text NULL,
  updated_at   bigint NOT NULL,
  seq          bigint NOT NULL,
  deleted      integer NOT NULL CHECK (deleted IN (0,1)),
  clk_at       bigint NOT NULL,
  clk_dev      text COLLATE "C" NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX sync_track_overrides_pull ON sync_track_overrides (user_id, seq);

CREATE TABLE sync_lyrics_pins (
  user_id       text COLLATE "C" NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      text COLLATE "C" NOT NULL CHECK (length(video_id) = 11),
  source        text NULL,
  ref           text NULL,
  start_time_ms integer NULL,
  updated_at    bigint NOT NULL,
  seq           bigint NOT NULL,
  deleted       integer NOT NULL CHECK (deleted IN (0,1)),
  clk_at        bigint NOT NULL,
  clk_dev       text COLLATE "C" NULL,
  PRIMARY KEY (user_id, video_id)
);

CREATE INDEX sync_lyrics_pins_pull ON sync_lyrics_pins (user_id, seq);
