-- Melogold database schema, SQLite.
-- Generated by scripts/gen-schema-sql.ts from src/db/migrations (npm run schema:sql). Do not edit.
-- Normative source: docs/API.md §9. Kysely creates kysely_migration and kysely_migration_lock itself.
-- A new database gets PRAGMA auto_vacuum = INCREMENTAL before the first table (src/db/dialect-sqlite.ts).

-- ===== 0001_core =============================================================

CREATE TABLE server_meta (
  key   TEXT NOT NULL PRIMARY KEY,
  value TEXT NOT NULL
) STRICT;

CREATE TABLE users (
  id                         TEXT NOT NULL PRIMARY KEY,
  login                      TEXT NOT NULL UNIQUE CHECK (length(login) BETWEEN 3 AND 64),
  password_hash              TEXT NOT NULL,
  auth_version               INTEGER NOT NULL DEFAULT 1,
  password_changed_at        INTEGER NOT NULL,
  recovery_code_hash         TEXT NOT NULL CHECK (length(recovery_code_hash) = 64),
  recovery_code_created_at   INTEGER NOT NULL,
  recovery_code_confirmed_at INTEGER NULL,
  created_by                 TEXT NOT NULL DEFAULT 'self',
  deleted_at                 INTEGER NULL,
  created_at                 INTEGER NOT NULL,
  updated_at                 INTEGER NOT NULL
) STRICT;

CREATE INDEX users_deleted ON users (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE devices (
  id                  TEXT NOT NULL PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hwid_hash           TEXT NOT NULL CHECK (length(hwid_hash) = 64),
  reported_name       TEXT NOT NULL CHECK (length(reported_name) BETWEEN 1 AND 64),
  custom_name         TEXT NULL CHECK (custom_name IS NULL OR length(custom_name) BETWEEN 1 AND 64),
  platform            TEXT NOT NULL CHECK (length(platform) BETWEEN 1 AND 16),
  os_version          TEXT NULL,
  model               TEXT NULL,
  client_version      TEXT NULL,
  linked_via          TEXT NOT NULL,
  linked_by_device_id TEXT NULL,
  created_at          INTEGER NOT NULL,
  last_seen_at        INTEGER NOT NULL,
  last_sync_at        INTEGER NULL,
  UNIQUE (user_id, hwid_hash)
) STRICT;

CREATE INDEX devices_last_seen ON devices (last_seen_at);

CREATE TABLE refresh_tokens (
  id                        TEXT NOT NULL PRIMARY KEY,
  user_id                   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id                 TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  token_hash                TEXT NOT NULL UNIQUE,
  expires_at                INTEGER NOT NULL,
  rotated_to_id             TEXT NULL,
  rotation_grace_expires_at INTEGER NULL,
  revoked_at                INTEGER NULL,
  confirmed_at              INTEGER NULL,
  created_at                INTEGER NOT NULL
) STRICT;

CREATE INDEX refresh_tokens_user ON refresh_tokens (user_id);

CREATE INDEX refresh_tokens_device ON refresh_tokens (device_id);

CREATE INDEX refresh_tokens_expires ON refresh_tokens (expires_at);

CREATE TABLE auth_throttle (
  scope        TEXT NOT NULL,
  key_hash     TEXT NOT NULL,
  failures     INTEGER NOT NULL DEFAULT 0,
  window_start INTEGER NOT NULL,
  locked_until INTEGER NULL,
  updated_at   INTEGER NOT NULL,
  PRIMARY KEY (scope, key_hash)
) STRICT;

-- ===== 0002_linking ==========================================================

CREATE TABLE device_links (
  id                      TEXT NOT NULL PRIMARY KEY,
  mode                    TEXT NOT NULL,
  status                  TEXT NOT NULL,
  token_hash              TEXT NOT NULL UNIQUE,
  code_hash               TEXT NOT NULL UNIQUE,
  poll_secret_hash        TEXT NULL UNIQUE,
  user_id                 TEXT NULL REFERENCES users(id) ON DELETE CASCADE,
  approver_device_id      TEXT NULL REFERENCES devices(id) ON DELETE SET NULL,
  claimant_hwid_hash      TEXT NULL,
  claimant_name           TEXT NULL,
  claimant_platform       TEXT NULL,
  claimant_os_version     TEXT NULL,
  claimant_model          TEXT NULL,
  claimant_client_version TEXT NULL,
  verify_code             TEXT NULL CHECK (verify_code IS NULL OR length(verify_code) = 2),
  deny_reason             TEXT NULL,
  creator_net             TEXT NULL,
  other_net               TEXT NULL,
  result_device_id        TEXT NULL,
  result_refresh_id       TEXT NULL,
  created_at              INTEGER NOT NULL,
  expires_at              INTEGER NOT NULL,
  claimed_at              INTEGER NULL,
  decided_at              INTEGER NULL,
  completed_at            INTEGER NULL
) STRICT;

CREATE INDEX device_links_expires ON device_links (expires_at);

CREATE INDEX device_links_user ON device_links (user_id);

CREATE INDEX device_links_approver ON device_links (approver_device_id);

CREATE INDEX device_links_net ON device_links (creator_net) WHERE creator_net IS NOT NULL;

-- ===== 0003_sync =============================================================

CREATE TABLE sync_heads (
  user_id    TEXT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  epoch      TEXT NOT NULL CHECK (length(epoch) = 8),
  seq        INTEGER NOT NULL DEFAULT 0,
  floor_seq  INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE sync_ops (
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seq         INTEGER NOT NULL,
  op_id       TEXT NOT NULL,
  device_id   TEXT NULL,
  device_name TEXT NULL,
  kind        TEXT NOT NULL CHECK (length(kind) BETWEEN 1 AND 64),
  payload     TEXT NOT NULL,
  status      TEXT NOT NULL,
  code        TEXT NULL,
  result      TEXT NULL,
  client_at   INTEGER NOT NULL,
  eff_at      INTEGER NOT NULL,
  base_seq    INTEGER NULL,
  pre_image   TEXT NULL,
  server_at   INTEGER NOT NULL,
  PRIMARY KEY (user_id, seq)
) STRICT;

CREATE UNIQUE INDEX sync_ops_op ON sync_ops (user_id, op_id);

CREATE INDEX sync_ops_server_at ON sync_ops (server_at);

CREATE TABLE sync_tracks (
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      TEXT NOT NULL CHECK (length(video_id) = 11),
  title         TEXT NOT NULL,
  artists_text  TEXT NULL,
  artists       TEXT NULL,
  album_id      TEXT NULL,
  album_title   TEXT NULL,
  duration_ms   INTEGER NULL,
  duration_text TEXT NULL,
  thumbnail_url TEXT NULL,
  explicit      INTEGER NOT NULL DEFAULT 0 CHECK (explicit IN (0,1)),
  video_type    TEXT NULL,
  stub          INTEGER NOT NULL DEFAULT 0 CHECK (stub IN (0,1)),
  seq           INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  PRIMARY KEY (user_id, video_id)
) STRICT;

CREATE INDEX sync_tracks_pull ON sync_tracks (user_id, seq);

CREATE TABLE sync_likes (
  user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id TEXT NOT NULL CHECK (length(video_id) = 11),
  liked    INTEGER NOT NULL CHECK (liked IN (0,1)),
  liked_at INTEGER NULL,
  seq      INTEGER NOT NULL,
  clk_at   INTEGER NOT NULL,
  clk_dev  TEXT NULL,
  PRIMARY KEY (user_id, video_id)
) STRICT;

CREATE INDEX sync_likes_pull ON sync_likes (user_id, seq);

CREATE TABLE sync_bookmarks (
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          TEXT NOT NULL CHECK (length(type) BETWEEN 1 AND 16),
  browse_id     TEXT NOT NULL CHECK (length(browse_id) BETWEEN 1 AND 64),
  bookmarked    INTEGER NOT NULL CHECK (bookmarked IN (0,1)),
  bookmarked_at INTEGER NULL,
  title         TEXT NULL,
  subtitle      TEXT NULL,
  thumbnail_url TEXT NULL,
  year          TEXT NULL,
  seq           INTEGER NOT NULL,
  clk_at        INTEGER NOT NULL,
  clk_dev       TEXT NULL,
  PRIMARY KEY (user_id, type, browse_id)
) STRICT;

CREATE INDEX sync_bookmarks_pull ON sync_bookmarks (user_id, seq);

CREATE TABLE sync_playlists (
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  id            TEXT NOT NULL,
  name          TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  browse_id     TEXT NULL,
  thumbnail_url TEXT NULL,
  created_at    INTEGER NOT NULL,
  deleted       INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
  deleted_at    INTEGER NULL,
  deleted_seq   INTEGER NULL,
  item_count    INTEGER NOT NULL DEFAULT 0,
  seq           INTEGER NOT NULL,
  clk_at        INTEGER NOT NULL,
  clk_dev       TEXT NULL,
  PRIMARY KEY (user_id, id)
) STRICT;

CREATE INDEX sync_playlists_pull ON sync_playlists (user_id, seq);

CREATE INDEX sync_playlists_live_browse ON sync_playlists (user_id, browse_id) WHERE deleted = 0 AND browse_id IS NOT NULL;

CREATE TABLE sync_playlist_items (
  user_id     TEXT NOT NULL,
  playlist_id TEXT NOT NULL,
  video_id    TEXT NOT NULL CHECK (length(video_id) = 11),
  present     INTEGER NOT NULL CHECK (present IN (0,1)),
  sort_key    TEXT NOT NULL CHECK (length(sort_key) BETWEEN 1 AND 64),
  added_at    INTEGER NOT NULL,
  seq         INTEGER NOT NULL,
  mem_seq     INTEGER NOT NULL,
  mem_at      INTEGER NOT NULL,
  mem_dev     TEXT NULL,
  pos_seq     INTEGER NOT NULL,
  pos_at      INTEGER NOT NULL,
  pos_dev     TEXT NULL,
  PRIMARY KEY (user_id, playlist_id, video_id),
  FOREIGN KEY (user_id, playlist_id) REFERENCES sync_playlists (user_id, id) ON DELETE CASCADE
) STRICT;

CREATE INDEX sync_items_pull ON sync_playlist_items (user_id, seq);

CREATE INDEX sync_items_order ON sync_playlist_items (user_id, playlist_id, sort_key, video_id) WHERE present = 1;

-- ===== 0004_playback =========================================================

CREATE TABLE playback_state (
  user_id            TEXT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  rev                INTEGER NOT NULL,
  cleared            INTEGER NOT NULL DEFAULT 0 CHECK (cleared IN (0,1)),
  device_id          TEXT NOT NULL,
  device_name        TEXT NULL,
  session_id         TEXT NOT NULL,
  queue_version      INTEGER NOT NULL CHECK (queue_version >= 0),
  queue              TEXT NOT NULL,
  idx                INTEGER NOT NULL CHECK (idx >= 0),
  position_ms        INTEGER NOT NULL CHECK (position_ms >= 0),
  duration_ms        INTEGER NULL,
  playing            INTEGER NOT NULL CHECK (playing IN (0,1)),
  state_at           INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL,
  handoff_device_id  TEXT NULL,
  handoff_session_id TEXT NULL,
  handoff_at         INTEGER NULL
) STRICT;

CREATE INDEX playback_state_updated ON playback_state (updated_at);

-- ===== 0005_history ==========================================================

CREATE TABLE play_events (
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id        TEXT NOT NULL,
  video_id        TEXT NOT NULL CHECK (length(video_id) = 11),
  played_at       INTEGER NOT NULL,
  play_time_ms    INTEGER NOT NULL CHECK (play_time_ms BETWEEN 1 AND 86400000),
  in_history      INTEGER NOT NULL CHECK (in_history IN (0,1)),
  counts_playtime INTEGER NOT NULL CHECK (counts_playtime IN (0,1)),
  device_id       TEXT NULL,
  seq             INTEGER NULL,
  received_at     INTEGER NOT NULL,
  PRIMARY KEY (user_id, event_id)
) STRICT;

CREATE INDEX play_events_pull ON play_events (user_id, seq) WHERE seq IS NOT NULL;

CREATE INDEX play_events_video ON play_events (user_id, video_id, played_at);

CREATE INDEX play_events_time ON play_events (user_id, played_at);

CREATE INDEX play_events_recv ON play_events (user_id, received_at);

CREATE INDEX play_events_idem ON play_events (received_at) WHERE in_history = 0;

CREATE TABLE play_stats (
  user_id        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id       TEXT NOT NULL CHECK (length(video_id) = 11),
  total_ms       INTEGER NOT NULL DEFAULT 0,
  last_played_at INTEGER NULL,
  seq            INTEGER NOT NULL,
  PRIMARY KEY (user_id, video_id)
) STRICT;

CREATE INDEX play_stats_pull ON play_stats (user_id, seq);

CREATE TABLE play_forgets (
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      TEXT NOT NULL CHECK (video_id = '*' OR length(video_id) = 11),
  events_before INTEGER NOT NULL,
  total_before  INTEGER NULL,
  seq           INTEGER NOT NULL,
  PRIMARY KEY (user_id, video_id)
) STRICT;

CREATE INDEX play_forgets_pull ON play_forgets (user_id, seq);

-- ===== 0006_lyrics ===========================================================

CREATE TABLE lyrics (
  id            TEXT NOT NULL PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id      TEXT NOT NULL CHECK (length(video_id) = 11),
  rev           INTEGER NOT NULL CHECK (rev >= 1),
  deleted       INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
  plain         TEXT NULL,
  plain_source  TEXT NULL,
  synced        TEXT NULL,
  synced_format TEXT NULL,
  synced_source TEXT NULL,
  start_time_ms INTEGER NULL,
  language      TEXT NULL,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX lyrics_user_video ON lyrics (user_id, video_id);

CREATE UNIQUE INDEX lyrics_user_rev ON lyrics (user_id, rev);

CREATE INDEX lyrics_video ON lyrics (video_id, updated_at);
